name: repub_admin
description: Flutter web admin interface for Repub package registry
publish_to: none
version: 0.1.0

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  repub_model:
  http: ^1.2.0
  go_router: ^14.7.2
  flutter_riverpod: ^2.6.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: true
