name: repub_migrate
description: Database migrations for repub package registry
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  postgres: ^3.5.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
