name: repub_auth
description: Authentication and authorization for repub package registry
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  repub_model:
    path: ../repub_model
  crypto: ^3.0.6
  shelf: ^1.4.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
