name: repub_cli
description: Admin CLI for repub package registry
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  repub_model:
    path: ../repub_model
  repub_storage:
    path: ../repub_storage
  repub_server:
    path: ../repub_server
  args: ^2.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
